def load_test_data
  @merchant = create(:merchant)
  @merchant1 = create(:merchant)
  @merchant2 = create(:merchant)
  @merchant3 = create(:merchant)
  @merchant4 = create(:merchant)
  @merchant5 = create(:merchant)
  @merchant6 = create(:merchant)
  @merchant7 = create(:merchant)
  
  @merchant_1 = Merchant.create!(name: "Geoff's Goodies")
  @merchant_2 = Merchant.create!(name: "Bubba's Boutique")
  @chochky = @merchant_1.items.create!(name: "chochky", description: "Useless", unit_price: 50)
  @spinner = @merchant_2.items.create!(name: "Fidget Spinner", description: "Spins", unit_price: 1)
  @bouncer = @merchant_2.items.create!(name: "Bouncy Ball", description: "bounces", unit_price: 2)
  @ball = @merchant1.items.create!(name: "Bouncy Ball", description: "bounces", unit_price: 2)

  @cust_1 = Customer.create!(first_name: "Dave", last_name: "Beckam")
  @cust_2 = Customer.create!(first_name: "Becky", last_name: "Beckam")
  @cust_3 = Customer.create!(first_name: "Steve", last_name: "Beckam")
  @cust_4 = Customer.create!(first_name: "Roger", last_name: "Beckam")
  @cust_5 = Customer.create!(first_name: "Winnona", last_name: "Beckam")
  @cust_6 = Customer.create!(first_name: "Bend_it", last_name: "Beckam")

  @items = create_list(:item, 5, merchant: @merchant)
  @items_2 = create_list(:item, 3, merchant: @merchant2)
  @item = create(:item, merchant: @merchant)
  @item_2 = create(:item, merchant: @merchant)
  @enabled_items = create_list(:item, 3, merchant: @merchant, status: 'enabled')
  @disabled_items = create_list(:item, 3, merchant: @merchant, status: 'disabled')
  
  @item1 = create(:item, unit_price: 10, merchant_id: @merchant1.id)
  @item2 = create(:item, unit_price: 50, merchant_id: @merchant2.id)
  @item3 = create(:item, unit_price: 100, merchant_id: @merchant3.id)
  @item4 = create(:item, unit_price: 200, merchant_id: @merchant4.id)
  @item5 = create(:item, unit_price: 300, merchant_id: @merchant5.id)
  @item6 = create(:item, unit_price: 400, merchant_id: @merchant6.id)
  @item7 = @merchant7.items.create!(name: "Item 7", description: "Item", unit_price: 10)
  @item8 = @merchant7.items.create!(name: "Item 8", description: "Item", unit_price: 20)
  @item9 = @merchant7.items.create!(name: "Item 9", description: "Item", unit_price: 30)
  
  @customer = Customer.create!(first_name: "John", last_name: "Smith")
  @customer1 = Customer.create!(first_name: "Johnny" , last_name: "Smith")

  @invoice_1 = @customer1.invoices.create!(status: 1)
  @invoice1 = @customer.invoices.create!(status: 1, created_at: "2023-08-07")
  @invoice2 = @customer.invoices.create!(status: 1, created_at: "2023-08-08")
  @invoice3 = @customer.invoices.create!(status: 1, created_at: "2023-08-11")
  @invoice4 = @customer.invoices.create!(status: 1, created_at: "2023-08-12")
  @invoice5 = @customer.invoices.create!(status: 1, created_at: "2023-08-14")
  @invoice6 = @customer.invoices.create!(status: 1, created_at: "2023-08-15")
  @invoice7 = @customer.invoices.create!(status: 1, created_at: "2023-08-09")
  @invoice8 = @customer.invoices.create!(status: 1, created_at: "2023-08-09")
  @invoice9 = @customer.invoices.create!(status: 1, created_at: "2023-08-12")
  @invoice10 = @customer.invoices.create!(status: 1, created_at: "2023-08-12")
  @invoice11 = @customer.invoices.create!(status: 1, created_at: "2023-08-12")
  @invoice12 = @customer.invoices.create!(status: 2, created_at: "2023-08-12")

  @invoice_item1 = InvoiceItem.create!(item_id: @item7.id, invoice_id: @invoice_1.id, quantity: 1, status: 2)
  @invoice_item2 = InvoiceItem.create!(item_id: @item8.id, invoice_id: @invoice_1.id, quantity: 2, status: 2)
  @invoice_item3 = InvoiceItem.create!(item_id: @item9.id, invoice_id: @invoice_1.id, quantity: 3, status: 2)
  @invoice_item4 = InvoiceItem.create!(item_id: @item9.id, invoice_id: @invoice11.id, quantity: 3, status: 2)

  
  InvoiceItem.create!(item_id: @item6.id, invoice_id: @invoice6.id, quantity: 7, unit_price: 400, status: 2)
  InvoiceItem.create!(item_id: @item5.id, invoice_id: @invoice5.id, quantity: 6, unit_price: 300, status: 2)
  InvoiceItem.create!(item_id: @item4.id, invoice_id: @invoice4.id, quantity: 4, unit_price: 200, status: 2)
  InvoiceItem.create!(item_id: @item3.id, invoice_id: @invoice3.id, quantity: 3, unit_price: 100, status: 2)
  InvoiceItem.create!(item_id: @item2.id, invoice_id: @invoice2.id, quantity: 2, unit_price: 50, status: 2)
  InvoiceItem.create!(item_id: @item1.id, invoice_id: @invoice1.id, quantity: 1, unit_price: 10, status: 2)
  
  InvoiceItem.create!(item_id: @item1.id, invoice_id: @invoice7.id, quantity: 1, unit_price: 10, status: 2)
  InvoiceItem.create!(item_id: @item1.id, invoice_id: @invoice8.id, quantity: 1, unit_price: 10, status: 2)
  InvoiceItem.create!(item_id: @item2.id, invoice_id: @invoice9.id, quantity: 1, unit_price: 50, status: 2)
  InvoiceItem.create!(item_id: @item2.id, invoice_id: @invoice10.id, quantity: 1, unit_price: 50, status: 2)
  InvoiceItem.create!(item_id: @ball.id, invoice_id: @invoice12.id, quantity: 5, unit_price: 50, status: 2)

  @invoice1.transactions.create!(result: 1)
  @invoice2.transactions.create!(result: 1)
  @invoice3.transactions.create!(result: 1)
  @invoice3.transactions.create!(result: 1)
  @invoice4.transactions.create!(result: 1)
  @invoice5.transactions.create!(result: 1)
  @invoice6.transactions.create!(result: 1)
  @invoice7.transactions.create!(result: 1)
  @invoice8.transactions.create!(result: 1)
  @invoice9.transactions.create!(result: 1)
  @invoice10.transactions.create!(result: 1)

  @discount_1 = @merchant1.bulk_discounts.create!(threshold: 10, discount: 20)
  @discount_2 = @merchant1.bulk_discounts.create!(threshold: 15, discount: 30)
  @discount_3 = @merchant1.bulk_discounts.create!(threshold: 1, discount: 5)
end